/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedLayoutImport } from './routes/_authenticated/_layout'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const AuthenticatedLayoutProductsIndexLazyImport = createFileRoute(
  '/_authenticated/_layout/products/',
)()
const AuthenticatedLayoutDashboardIndexLazyImport = createFileRoute(
  '/_authenticated/_layout/dashboard/',
)()
const AuthenticatedLayoutCustomersIndexLazyImport = createFileRoute(
  '/_authenticated/_layout/customers/',
)()

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AuthenticatedLayoutRoute = AuthenticatedLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedLayoutProductsIndexLazyRoute =
  AuthenticatedLayoutProductsIndexLazyImport.update({
    path: '/products/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/_layout/products/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedLayoutDashboardIndexLazyRoute =
  AuthenticatedLayoutDashboardIndexLazyImport.update({
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/_layout/dashboard/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedLayoutCustomersIndexLazyRoute =
  AuthenticatedLayoutCustomersIndexLazyImport.update({
    path: '/customers/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/_layout/customers/index.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_layout': {
      preLoaderRoute: typeof AuthenticatedLayoutImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_layout/customers/': {
      preLoaderRoute: typeof AuthenticatedLayoutCustomersIndexLazyImport
      parentRoute: typeof AuthenticatedLayoutImport
    }
    '/_authenticated/_layout/dashboard/': {
      preLoaderRoute: typeof AuthenticatedLayoutDashboardIndexLazyImport
      parentRoute: typeof AuthenticatedLayoutImport
    }
    '/_authenticated/_layout/products/': {
      preLoaderRoute: typeof AuthenticatedLayoutProductsIndexLazyImport
      parentRoute: typeof AuthenticatedLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AuthenticatedRoute.addChildren([
    AuthenticatedLayoutRoute.addChildren([
      AuthenticatedLayoutCustomersIndexLazyRoute,
      AuthenticatedLayoutDashboardIndexLazyRoute,
      AuthenticatedLayoutProductsIndexLazyRoute,
    ]),
  ]),
])

/* prettier-ignore-end */
